### ISSUE TITLE
Разные кодировки в исходных файлах

### ISSUE THREAD

**Issue by saigon-89** [valabsoft/code-ai-400393#12]
В файле mrcv-imgcollection.cpp корректное отображение русских символов (UTF).
В остальных src/ файлах кодировка Windows-1251.
Предложение перейти на общую платформонезависимую кодировку UTF.

**Comment by valabsoft** [comment]
OK, принимается. Кирилл, подготовь пожалуйста инструкции по настройке редакторов Qt, Visual Studio, Visual Studio Code под Windows.
Я проблему с кодировкой наблюдаю только в Source Tree, но лишним не будет.

**Comment by VASoftLab** [comment]
Все файлы проекта в кодировке UTF
