### ISSUE TITLE
Проблемы doxygen-документации

### ISSUE THREAD

**Issue by saigon-89** [valabsoft/code-ai-400393#13]
В файлах .cpp присутсвует документация, хотя документировать нужно содержимое заголовочных файлов (константы, прототипы функций). Также у файлов разный формат документации. Для примера прикрепляю пример документации, которую использовали при сборке pdf-документа для конечного пользователя на предприятии:

```
/**
 * @file
 * @brief Линейный распределитель памяти (Linear Memory Allocator, LMA)
 * @details  Компонент представляет собой низкоуровневый инструмент линейного
 * распределения памяти. Под памятью подразумевается не ресурс
 * (физическая или виртуальная память), а абстракция в виде
 * диапазонов [адрес:адрес+размер) и контейнера для их хранения.
 *
 * Данный инструмент является архитектурным решением, которое позволяет
 * сократить дублирование кода, и не может быть напрямую связан с
 * верхнеуровневыми требованиями, так как формальные связи будут установлены
 * неявным способом со множеством требований, тем самым раскрывая детали
 * реализации.
 */

#ifndef _ASSIST_LMA_H
#define _ASSIST_LMA_H

#include <errno.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>

/**
 * @brief Описатель распределителя LMA
 */
typedef struct lma {
  uintptr_t base; /*!< Базовый адрес области памяти распределителя */
  size_t size; /*!< Размер области памяти распределителя */
  uintptr_t free_begin; /*!< Первый свободный адрес с начала */
  uintptr_t free_end; /*!< Первый недоступный адрес с конца */
  uintptr_t last_addr; /*!< Адрес последней выделенной памяти с начала */
  uintptr_t last_raddr; /*!< Адрес последней выделенной памяти с конца */
  bool can_free; /*!< Флаг: распределитель может возвращать выделенную память */
} lma_t;

/**
 * @brief Инициализация распределителя памяти (полная)
 * @details Инициализировать распределитель памяти \a lma согласно заданным
 * параметрам \a addr и \a size, которые описывают область памяти, использовав
 * функцию \ref _init.
 * @note С поддержкой освобождения памяти (lma_free).
 *
 * @param[in,out] lma Описатель распределителя.
 * @param[in] addr Адрес начала области памяти распределителя.
 * @param[in] size Размер области памяти распределителя.
 *
 * @return Возвращает 0 в случае успеха, иначе - код ошибки установленный
 * функцией \ref _init.
 */
errno_t lma_init(lma_t *lma, uintptr_t addr, size_t size);

/**
 * @brief Сброс распределителя в исходное состояние
 * @details Сбросить значения занятой памяти распределителя \a lma в исходное
 * состояние. Вся выделенная ранее памяти (указатели) становится невалидной.
 *
 * @param[in,out] lma Описатель распределителя.
 */
void lma_reset(lma_t *lma);

/**
 * @brief Освобождение памяти
 * @details Освободить память распределителя lma начинающуюся с адреса addr.
 * Освобождение возможно только в порядке обратном выделению.
 *
 * @param[in,out] lma Распределитель памяти.
 * @param[in] addr Адрес начала освобождаемой области памяти.
 *
 * @return Возвращает 0 в случае успеха, иначе код ошибки.
 * @retval ENOTSUP Для заданного распределителя освобождение не поддерживается.
 * @retval ENOMEM Отсутствует память, которую можно освободить.
 * @retval ERANGE Некорректный адрес addr.
 */
errno_t lma_free(lma_t *lma, uintptr_t addr);

/**
 * @brief Получение занятого количества памяти распределителя
 * @details Выдать объем выделенной через распределитель \a lma памяти с момента
 * инициализации \ref lma_init или сброса \ref lma_reset.
 *
 * @param[in] lma Описатель распределителя.
 *
 * @return Возвращает размер занятой памяти в распределителе.
 */
size_t lma_used_size(const lma_t *lma);

#endif /* _ASSIST_LMA_H */
```

**Также в качестве предложения прикрепляю требования к документации:**
1. Описания должны содержаться только в h-файле.

2. Основные правила оформления doxygen-описания для МОДУЛЕЙ:

- каждый модуль должен начинаться с тэга @file (без параметров)
- должен быть как brief, так и details
- brief должен кратко описывать суть модуля
- details должен описывать задачи, которые решаются функциями модуля, а также описывать где могут использоваться функции модуля (details связывает все функции модуля между собой); помимо этого, должно быть указано от состояния каких модулей или компонентов зависит поведение описываемого модуля.

3. Основные правила оформления doxygen-описания для ФУНКЦИЙ:

- должен быть как brief, так и details
- brief должен описывать цель/назначение функции, но без подробностей, в частности без ссылок на параметры
- brief должен начинаться с отглагольного существительного (например, "Расчет размера пула", существительное "расчет" от глагола "рассчитать")
- details должен описывать наблюдаемое поведение функции относительно входов и выходов (параметры и возращаемое значение), а также изменение состояния модуля или компонента (глобальные переменные); текст в details следует приводить в форме должествования, а слово "функция" применительно описываемой функции стараться не использовать или использовать крайне редко. Пример details для функции копирования данных: "Скопировать данные, расположенные в области [src:src+size), в область [dst:dst+size)"

4. Константы, макросы, типы также должны быть описаны в формате doxygen (в большинстве случаев для их описания достаточно тэга brief).

**Comment by valabsoft** [comment]
Не все функции имеют заголовки в h файлах. Но все функции должны быть
задукоментированы. В документах по стандартам кодирования приведен шаблон.
Не усложняем.

сб, 3 авг. 2024 г., 16:47 saigon-89 ***@***.***>:
